BuyFS/Patrician.WebApp/Controllers/CategoryController.cs
using Commerce.BusinessLogicLayer.Abstract;
using Microsoft.AspNetCore.Mvc;
using Patrician.WebApp.Models;

namespace Patrician.WebApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;

        //using both in order to pull products by category id
        public CategoryController(IProductService _productservice, ICategoryService _categoryservice)
        {
            this.productService = _productservice;
            this.categoryService = _categoryservice;
        }
        public IActionResult Index(int id)
        {
            //In order to tell the webapp that the category Id is the category id defined for categories
            CategoryDetailsViewModel categorymodel = new CategoryDetailsViewModel();
            categorymodel.Category = categoryService.GetCategory().Data.ToList();

            //previously made GetProductbyCategoryId function used here, allowing us to list products by category id.
            var result = productService.GetProductbyCategoryId(id);
            switch (result.ResultType)
            {
                case BuyFS.Core.Constant.EntityResultType.Success:
                    categorymodel.ProductDto = result.Data.ToList();
                    return View(categorymodel);
                case BuyFS.Core.Constant.EntityResultType.Error:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NotFound:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NonValidation:
                    break;
                case BuyFS.Core.Constant.EntityResultType.Warning:
                    break;
                default:
                    break;
            }
            return View();

        }
    }
}

BuyFS/Patrician.WebApp/Controllers/ProductController.cs
using Commerce.BusinessLogicLayer.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace Patrician.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;

        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Detail(int id)
        {
            string[] Images = new string[] { "ProductImage" };
            var result = productService.GetEntity(x => x.Id == id, Images);
            switch (result.ResultType)
            {
                case BuyFS.Core.Constant.EntityResultType.Success:
                    var entity = result.Data.ToList()[0];
                    return View(entity);
                case BuyFS.Core.Constant.EntityResultType.Error:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NotFound:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NonValidation:
                    break;
                case BuyFS.Core.Constant.EntityResultType.Warning:
                    break;
                default:
                    break;
            }
            return View();
        }
    }
}

BuyFS/Patrician.WebApp/Views/Category/Index.cshtml
@model CategoryDetailsViewModel
@{
    ViewData["Title"] = "Index";
}

<!-- Breadcrumb Section Begin -->
<div class="breacrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <a href="#"><i class="fa fa-home"></i> Home</a>
                    <span>Shop</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section Begin -->

<!-- Product Shop Section Begin -->
<section class="product-shop spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-8 order-2 order-lg-1 produts-sidebar-filter">
                <div class="filter-widget">
                    <h4 class="fw-title">Categories</h4>
                    <ul class="filter-catagories">
                        @foreach (var item in Model.Category)
                        {
                            <li><a asp-route-id="@item.Id" asp-action="Index" asp-controller="Category">@item.Name</a></li>
                        }
                    </ul>
                </div>
            </div>
            <div class="col-lg-9 order-1 order-lg-2">
                <div class="product-show-option">
                    <div class="row">
                        <div class="col-lg-7 col-md-7">
                            <div class="select-option">
                                <select class="sorting">
                                    <option value="">Default Sorting</option>
                                </select>
                                <select class="p-show">
                                    <option value="">Show:</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-5 col-md-5 text-right">
                            <p>Show 01- 09 Of 36 Product</p>
                        </div>
                    </div>
                </div>
                <div class="product-list">
                    @foreach (var item in Model.ProductDto)
                    {
                        <div class="col-lg-4 col-sm-6">
                            <div class="product-item">
                                <div class="pi-pic">
                                    <img src="@item.ImageURL" alt="">
                                    <div class="sale pp-sale">Sale</div>
                                    <div class="icon">
                                        <i class="icon_heart_alt"></i>
                                    </div>
                                    <ul>
                                        <li class="w-icon active"><button onclick="AddToBasket(@item.Id, 1)"><i class="icon_bag_alt"></i></button></li>
                                        <li class="quick-view"><a asp-route-id="@item.Id" asp-controller="Product" asp-action="Detail">+ Quick View</a></li>
                                        <li class="w-icon"><a href="#"><i class="fa fa-random"></i></a></li>
                                    </ul>
                                </div>
                                <div class="pi-text">
                                    <div class="catagory-name">@item.CategoryName</div>
                                    <a href="#">
                                        <h5>@item.Name</h5>
                                        <h5>In Stock: @item.Stock</h5>
                                    </a>
                                    <div class="product-price">
                                        $@item.Price
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div class="loading-more">
                    <i class="icon_loading"></i>
                    <a href="#">
                        Loading More
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Product Shop Section End -->

<!-- Partner Logo Section Begin -->
<div class="partner-logo">
    <div class="container">
        <div class="logo-carousel owl-carousel">
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="img/logo-carousel/logo-1.png" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="img/logo-carousel/logo-2.png" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="img/logo-carousel/logo-3.png" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="img/logo-carousel/logo-4.png" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="img/logo-carousel/logo-5.png" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Partner Logo Section End -->