BuyFS/Patrician.WebApp/Models/HeaderViewModel.cs
using BuyFS.Entity.POCO;
using Commerce.BusinessLogicLayer.Abstract;
using System.Collections.Generic;

namespace Patrician.WebApp.Models
{
    public class HeaderViewModel
    {
        public List<Category> Categorylist { get; set; }
    }
}

BuyFS/Patrician.WebApp/Component/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Patrician.WebApp.Component
{
    //footer view component calls to footer component in view folder and invokes that view.
    public class FooterViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

BuyFS/Patrician.WebApp/Component/HeaderViewComponent.cs
using Commerce.BusinessLogicLayer.Abstract;
using Microsoft.AspNetCore.Mvc;
using Patrician.WebApp.Models;
using System.Linq;

namespace Patrician.WebApp.Component
{
    //header view component calls to header component in view folder and sources that view.
    public class HeaderViewComponent:ViewComponent
    {
        private readonly ICategoryService categoryService;

        public HeaderViewComponent(ICategoryService _categoryservice)
        {
            categoryService = _categoryservice;
        }

        public IViewComponentResult Invoke()
        {
            HeaderViewModel headermodel = new HeaderViewModel();
            var categories = categoryService.GetCategory();

            switch (categories.ResultType)
            {
                case BuyFS.Core.Constant.EntityResultType.Success:
                    headermodel.Categorylist = categories.Data.ToList();
                    break;
                case BuyFS.Core.Constant.EntityResultType.Error:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NotFound:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NonValidation:
                    break;
                case BuyFS.Core.Constant.EntityResultType.Warning:
                    break;
                default:
                    break;
            }
            return View(headermodel);
        }
    }
}

BuyFS/Patrician.WebApp/Controllers/BasketController.cs
using BuyFS.Entity.DTO;
using BuyFS.Entity.POCO;
using Commerce.BusinessLogicLayer.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Patrician.WebApp.Controllers
{
    [Authorize(Roles = "UserApp")]

    public class BasketController : Controller
    {
        private readonly IBasketService basketService;
        private readonly IProductService productService;
        private readonly UserManager<AppClient> userManager;

        public BasketController(IBasketService basketService, IProductService productService, UserManager<AppClient> userManager)
        {
            this.basketService = basketService;
            this.productService = productService;
            this.userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> AddToBasket(int count, int productId)
        {
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            var result = basketService.AddToBasket(new BasketDto
            {
                Count = count,
                ProductId = productId,
                ClientId = user.Id
            });

            switch (result.ResultType)
            {
                case BuyFS.Core.Constant.EntityResultType.Success:
                    return Ok(result.Data);
                case BuyFS.Core.Constant.EntityResultType.Error:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NotFound:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NonValidation:
                    break;
                case BuyFS.Core.Constant.EntityResultType.Warning:
                    break;
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> RefreshBasketCount()
        {
            var u = await userManager.FindByNameAsync(User.Identity.Name);
            var result = basketService.Get(u.Id);
            switch (result.ResultType)
            {
                case BuyFS.Core.Constant.EntityResultType.Success:
                    return Ok(result.Data.Sum(x => x.Count));
                case BuyFS.Core.Constant.EntityResultType.Error:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NotFound:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NonValidation:
                    break;
                case BuyFS.Core.Constant.EntityResultType.Warning:
                    break;
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ActualBasket()
        {
            var u = userManager.FindByNameAsync(User.Identity.Name);
            var result = productService.GetBasketByProduct(u.Id);

            switch (result.ResultType)
            {
                case BuyFS.Core.Constant.EntityResultType.Success:
                    return View(result.Data);
                case BuyFS.Core.Constant.EntityResultType.Error:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NotFound:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NonValidation:
                    break;
                case BuyFS.Core.Constant.EntityResultType.Warning:
                    break;
            }
            return NotFound();
        }

        public async Task<IActionResult> CountChange(int id, int count)
        {
            var u = await userManager.FindByNameAsync(User.Identity.Name);
            var result = basketService.Update(count, id, u.Id);
            switch (result.ResultType)
            {
                case BuyFS.Core.Constant.EntityResultType.Success:
                    return Ok();
                case BuyFS.Core.Constant.EntityResultType.Error:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NotFound:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NonValidation:
                    break;
                case BuyFS.Core.Constant.EntityResultType.Warning:
                    break;
            }
            return View();
        }
    }
}

BuyFS/Patrician.WebApp/Controllers/CategoryController.cs
using Commerce.BusinessLogicLayer.Abstract;
using Microsoft.AspNetCore.Mvc;
using Patrician.WebApp.Models;

namespace Patrician.WebApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;

        //using both in order to pull products by category id
        public CategoryController(IProductService _productservice, ICategoryService _categoryservice)
        {
            this.productService = _productservice;
            this.categoryService = _categoryservice;
        }
        public IActionResult Index(int id)
        {
            //In order to tell the webapp that the category Id is the category id defined for categories
            CategoryDetailsViewModel categorymodel = new CategoryDetailsViewModel();
            categorymodel.Category = categoryService.GetCategory().Data.ToList();

            //previously made GetProductbyCategoryId function used here, allowing us to list products by category id.
            var result = productService.GetProductbyCategoryId(id);
            switch (result.ResultType)
            {
                case BuyFS.Core.Constant.EntityResultType.Success:
                    categorymodel.ProductDto = result.Data.ToList();
                    return View(categorymodel);
                case BuyFS.Core.Constant.EntityResultType.Error:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NotFound:
                    break;
                case BuyFS.Core.Constant.EntityResultType.NonValidation:
                    break;
                case BuyFS.Core.Constant.EntityResultType.Warning:
                    break;
                default:
                    break;
            }
            return View();

        }
    }
}

BuyFS/Patrician.WebApp/Views/Shared/Components/Header/Default.cshtml
@model HeaderViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Header Section Begin -->
<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="ht-left">
                <div class="mail-service">
                    <i class=" fa fa-envelope"></i>
                    yildizhakan88@gmail.com
                </div>
                <div class="phone-service">
                    <i class=" fa fa-phone"></i>
                    +90 536 7849327
                </div>
            </div>
            <div class="ht-right">
                @if (User.Identity.IsAuthenticated)
                {

                    <a asp-controller="Account" asp-action="LogOut" class="login-panel"><i class="fa fa-user"></i>@User.Identity.Name</a>
                }
                else
                {
                    <a asp-controller="Account" asp-action="Login" class="login-panel"><i class="fa fa-user"></i>Login</a>
                }
                <div class="lan-selector">
                    <select class="language_drop" name="countries" id="countries" style="width:300px;">
                        <option value='yt' data-image="img/flag-1.jpg" data-imagecss="flag yt"
                                data-title="English">
                            English
                        </option>
                        <option value='yu' data-image="img/flag-2.jpg" data-imagecss="flag yu"
                                data-title="Bangladesh">
                            German
                        </option>
                    </select>
                </div>
                <div class="top-social">
                    <a href="#"><i class="ti-facebook"></i></a>
                    <a href="#"><i class="ti-twitter-alt"></i></a>
                    <a href="#"><i class="ti-linkedin"></i></a>
                    <a href="#"><i class="ti-pinterest"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="logo">
                        <a href="./index.html">
                            <img src="img/logo.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-7">
                    <div class="advanced-search">
                        <button type="button" class="category-btn">All Categories</button>
                        <div class="input-group">
                            <input type="text" placeholder="What do you need?">
                            <button type="button"><i class="ti-search"></i></button>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 text-right col-md-3">
                    <ul class="nav-right">
                        <li class="heart-icon">
                            <a href="#">
                                <i class="icon_heart_alt"></i>
                                @*<span></span>*@
                            </a>
                        </li>
                        <li class="cart-icon">
                            <a href="#">
                                <i class="icon_bag_alt"></i>
                                <span id="#baskt"></span>
                            </a>
                            @*<div class="cart-hover">
                                <div class="select-items">
                                    <table>
                                        <tbody>
                                            <tr>
                                                <td class="si-pic"><img src="img/select-product-1.jpg" alt=""></td>
                                                <td class="si-text">
                                                    <div class="product-selected">
                                                        <p>$60.00 x 1</p>
                                                        <h6>Kabino Bedside Table</h6>
                                                    </div>
                                                </td>
                                                <td class="si-close">
                                                    <i class="ti-close"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="si-pic"><img src="img/select-product-2.jpg" alt=""></td>
                                                <td class="si-text">
                                                    <div class="product-selected">
                                                        <p>$60.00 x 1</p>
                                                        <h6>Kabino Bedside Table</h6>
                                                    </div>
                                                </td>
                                                <td class="si-close">
                                                    <i class="ti-close"></i>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="select-total">
                                    <span>total:</span>
                                    <h5>$120.00</h5>
                                </div>
                                <div class="select-button">
                                    <a href="#" class="primary-btn view-card">VIEW CARD</a>
                                    <a href="#" class="primary-btn checkout-btn">CHECK OUT</a>
                                </div>
                            </div>*@
                        </li>
                        <li class="cart-price">$150.00</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="nav-item">
        <div class="container">
            <div class="nav-depart">
                <div class="depart-btn">
                    <i class="ti-menu"></i>
                    <span>All departments</span>
                    <ul class="depart-hover">
                        <li class="active"><a href="#">Women’s Clothing</a></li>
                        <li><a href="#">Men’s Clothing</a></li>
                        <li><a href="#">Underwear</a></li>
                        <li><a href="#">Kid's Clothing</a></li>
                        <li><a href="#">Brand Fashion</a></li>
                        <li><a href="#">Accessories/Shoes</a></li>
                        <li><a href="#">Luxury Brands</a></li>
                        <li><a href="#">Brand Outdoor Apparel</a></li>
                    </ul>
                </div>
            </div>
            <nav class="nav-menu mobile-menu">
                <ul>
                    <li class="active"><a href="./index.html">Home</a></li>
                    <li><a href="./shop.html">Shop</a></li>
                    <li>
                        <a href="#">Categories</a>
                        <ul class="dropdown">
                            @if (Model.Categorylist != null)
                            {
                                foreach (var item in Model.Categorylist)
                                {
                                    <li><a asp-route-id="@item.Id" asp-action="Index" asp-controller="Category">@item.Name</a></li>
                                }
                            }
                        </ul>
                    </li>
                    <li><a href="./contact.html">Contact</a></li>
                    <li>
                        <a href="#">Pages</a>
                        <ul class="dropdown">
                            <li><a href="./blog-details.html">Blog Details</a></li>
                            <li><a asp-action="ActualBasket" asp-controller="Basket">Shopping Cart</a></li>
                            <li><a href="./check-out.html">Checkout</a></li>
                            <li><a href="./faq.html">Faq</a></li>
                            <li><a asp-action="Register" asp-controller="Account">Register</a></li>
                            <li><a asp-action="Login" asp-controller="Account">Login</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <div id="mobile-menu-wrap"></div>
        </div>
    </div>
</header>
<!-- Header End -->